// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AdmissionContext))]
    partial class ApplicantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WebApp.Data.Entities.ApplicantsCurrent", b =>
                {
                    b.Property<int>("Program")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Consent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Individual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Math")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicsIct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Russian")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Program", "ApplicantId");

                    b.ToTable("ApplicantsCurrent");
                });
#pragma warning restore 612, 618
        }
    }
}
